language: java
jdk:
  - openjdk6
before_script:
  - "sh -e /etc/init.d/Xvfb :1 &"
  - "export DISPLAY=:1"  
script: mvn test
install: mvn -DskipTests=true install
branches:
  only:
    - master
notifications:
  email:
    - kunz@ideadapt.net