language: java
jdk:
  - openjdk6
env: DISPLAY=:99.0
# customized to let the maven-osgi-test-plugin skip tests
install: mvn install -Dmaven.test.skip=true
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
# customized to explicitly call maven-osgi-test-plugin test goal: mvn clean compile package org.sonatype.tycho:maven-osgi-test-plugin:test
script: mvn integration-test verify -Pcoverage
branches:
  only:
    - master
notifications:
  email:
    - kunz@ideadapt.net