language: java
jdk:
  - openjdk6
env: DISPLAY=:99.0
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script: mvn test
install: mvn -DskipTests=true install
branches:
  only:
    - master
notifications:
  email:
    - kunz@ideadapt.net