language: java
jdk:
  - openjdk6
env: DISPLAY=:99.0
install: mvn install -Dmaven.test.skip=true
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script: mvn test
branches:
  only:
    - master
notifications:
  email:
    - kunz@ideadapt.net