language: java
jdk:
  - oraclejdk7
before_script:
  - "export DISPLAY:=99.0"
  - "sh -e /etc/init.d/xvfb start"
script: mvn test
install: mvn -DskipTests=true install
branches:
  only:
    - master
notifications:
  email:
    - kunz@ideadapt.net